### ISSUE TITLE
Trade-Ins not working properly

### ISSUE THREAD

**Issue by fetchwireless** [Repair-DeskPOS/RepairDesk-Bugs#81] opened 2016-11-04 04:31 UTC
We have a few problems with trade-ins

1. Fails to set up the trade in stating it is due to the customer contact details missing. even for a customer that is a previous trade in customer.

2.  The cost line constantly clears out the details so we are never sure if the cost was deducted from the daily cash count.

**Comment by Repair-Desk** [comment] 2016-11-06 11:30
@HafizAnas please review and assign it to @imiamran

**Comment by HafizAnas** [comment] 2016-11-09 05:13
Hi @fetchwireless 

I have tried many times at my end but I am not able to reproduce this issue.
Please can you share screenshot or video regarding this issue, if possible

**Comment by fetchwireless** [comment] 2016-11-09 05:30
We did a trade in today and it didn't work properly.  We had to do a manual
out for the cash payout.  I will ask the staff to record a video tomorrow

On Nov 9, 2016 12:14 AM, "HafizAnas" <notifications@github.com> wrote:

Hi @fetchwireless <https://github.com/fetchwireless>

I have tried many times at my end but I am not able to reproduce this issue.
Please can you share screenshot or video regarding this issue, if possible

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/81#issuecomment-259335482>,
or mute the thread

**Comment by Repair-Desk** [comment] 2016-11-14 03:02
@fetchwireless i am closing this issue and in case you face this issue again. Please upload the video so we can fix it for you.

**Closed** 2016-11-14 03:02 UTC
Labels: bug, Customer Updated - Waiting For further information, Medium Priority
