### ISSUE TITLE
Help to Replicate Issues and Fixing

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#42] opened 2016-10-24 06:30 UTC
Hi @HafizAnas ,

As discussed Andrew from Pimp My Gadget is one of our good customers. He is facing few issues on POS that are hard to replicate and issues are just on his personal account.
I have taken permission from him to use his account. You can use RepairDesk Test customer for orders. Can you please login and try to replicate following issues. Once you figure our the problem, can you get them fixed.

_**\* I will send you login details in Personal Message***_
Few common items he use are:-
Misc
Merc18
Phonecase
Charger

1: Once he searches item from POS and change quantity / price repetitively, Items disappears from the list. It just happens sometimes.
2: Sometimes he faces "Payment Error" when he checkout. **Check screenshot attached.**
It usually occurs when you put some products in the transaction and click checkout if the value displays zero (although the products have got prices) sometimes the prices are not added up and this is when the issue occurs, it doesn't matter if you change the price to the correct one it still occurs 
3: Sometimes when checkout line item doesn't display on Mini Receipt. **Check screenshot attached.**
4: Sometimes order total is different from the total this is displayed on checkout screen. This one just happened when regularly checking out, the same was calculated incorrectly. **Check screenshot attached.**

![invalid payment](https://cloud.githubusercontent.com/assets/22955861/19635616/1939f710-99dd-11e6-9c22-e4e3afb6bd30.jpg)
![error payment](https://cloud.githubusercontent.com/assets/22955861/19635617/193e4356-99dd-11e6-8aab-6ac156f515d6.jpg)
![receipt](https://cloud.githubusercontent.com/assets/22955861/19635618/19407c5c-99dd-11e6-946b-1373d17aa423.jpg)

**Comment by HafizAnas** [comment] 2016-10-31 10:35
Dear @Uzair-RepairDesk 

I have reviewed with different scenarios but I am not able to reproduce these issues except number 2 and assign to developer. I have also noted down these issue at my end if i find in future during testing then I will try to fix them asap.

**Comment by andrewg1639** [comment] 2016-10-31 11:02
Thanks guys, issue #4&3 are not as important but #1 is extremely important.

Someone else (Jonathon white) has reported the same issue on the RepairDesk user group in Facebook.

We are having issue #1 with roughly 25% of transactions we do, it's extremely frustrating for our staff as sometimes it can happen 3-4 times in one transaction.

I've demonstrated the issue to Uzair through teamviewer and he was also able to see it happen.

Thanks
Andrew

**Comment by Uzair-RepairDesk** [comment] 2016-10-31 11:25
Hi Andrew @andrewg1639 , 
Thanks for your quick response. @HafizAnas As discussed, can you please give another try from Andrew account and see if you are able to replicate the issue # 1. Thanks

**Comment by HafizAnas** [comment] 2016-10-31 11:38
Hi Andrew @andrewg1639 
Sorry for inconvenience. Let me check one more time for you, I will try my best to replicate this issue and solve it asap that is panic for you.

**Comment by HafizAnas** [comment] 2016-11-02 05:52
Hi Andrew @andrewg1639 
I tried again to replicate the 1st issue but I am not able to catch it. Please make a gif image or video if you face this again so we can look into it

**Comment by Repair-Desk** [comment] 2016-11-10 01:11
@HafizAnas Here are the videos: https://www.youtube.com/watch?v=KqhOLyrP0Gc

I believe you have recently assigned this task to imran over asana as well

**Comment by itskamran** [comment] 2016-12-16 07:16
Dear @andrewg1639,

Issue has been resolved.

**Closed by itskamran** 2016-12-16 07:16 UTC
Labels: bug, Urgent
