### ISSUE TITLE
Tax showing up as due amount even after full payment

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#11] opened 2016-10-20 09:08 UTC
Even after full payment, amount equal to tax shows up in due amount.

When the client gives a 100% discount to an accessory it doesn't take the tax off on the invoice after it is created. It looks fine initially on the POS but when he reviewd the invoice later, it has a small amount due, and this is always the tax amount for the discounted product.

It appears to be a Tax issue. Client is saying that there are other invoices that don't have discounts where it does it. It has got 0 in the tax section even though it has selected the correct tax.

![](https://cloud.githubusercontent.com/assets/21986026/19551576/4ab6e23c-96c5-11e6-8313-0f153a6900f2.png)

**Comment by Repair-Desk** [comment] 2016-10-27 09:52
when giving 100% discount to customer and checking out, it gives error.
please review
![untitled](https://cloud.githubusercontent.com/assets/21986026/19762833/060176da-9c55-11e6-80a1-45b6036b71b9.png)

**Comment by aishahanif** [comment] 2016-10-31 04:54
Dear Anas,
please verify the issue because same issue is not reproduced on my end.

**Comment by HafizAnas** [comment] 2016-10-31 07:48
Dear @aishahanif 
when we add an tax inclusive accessory item on POS and give 100% discount, Click on check out and make full payment. System returns error as you can see in above screenshot.

**Comment by aishahanif** [comment] 2016-11-09 12:08
@HafizAnas , 
Said issue "when we add an tax inclusive accessory item on POS and give 100% discount, Click on check out and make full payment. System returns error as you can see in above screenshot." is fixed and live on staging please review.

above client  said issue is not reproduced on my end. please provide the steps.

**Comment by HafizAnas** [comment] 2016-11-10 08:18
@Fazal-RepairDesk 
Reported Issue regarding discount has been fixed on staging and we will live it asap but I am not able to reproduce second issue " Tax showing as due amount" .

**Closed** 2016-11-11 20:41 UTC
Labels: bug, not reproduced, Urgent
