### ISSUE TITLE
Issue With Trade-In Deposits

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#175] opened 2016-12-20 18:30 UTC
Had a phone for sale at £450.00. Sold it through the trade in section on RD but customer only gave me £20 deposit. When I do end of day it comes up as sold for the full amount on register sales and sales summary. Still shows I only took the £20.00 This means I would be looking for £430.00 when cashing up?

**Comment by Repair-Desk** [comment] 2016-12-20 18:31
@itskamran can you assign it to fayyaz

**Comment by itskamran** [comment] 2016-12-20 18:33
Dear @Repair-Desk , Assigned to fayaz here and on asana. Thanks

**Comment by HafizAnas** [comment] 2016-12-23 10:27
@Repair-Desk 
we are not able to reproduce this issue at my end and we have also confirmed from client account it's working fine.

**Closed** 2016-12-29 11:21 UTC
Labels: not reproduced
